list/urls.py
from django.urls import path

from .views import CatalogueListView, RoleListView, SubjectListView, OrgTypeListView, SavedQueries

app_name = 'list'
urlpatterns = [
    path('subjects/', SubjectListView.as_view(), name='subjects'),
    path('roles/', RoleListView.as_view(), name='roles'),
    path('catalogues/', CatalogueListView.as_view(), name='catalogues'),
    path('orgtypes/', OrgTypeListView.as_view(), name='orgtypes'),
    path('queries/', SavedQueries.as_view(), name='savedqueries')
]

siteedit2/urls.py
from urllib.parse import urljoin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import core.views
from core.helper import media_serv

urlpatterns = [
    path('', RedirectView.as_view(url='/login/dashboard')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('repositories/', include('institution.urls')),
    path('location/', include('location.urls')),
    path('person/', include('person.urls')),
    path('publication/', include('publication.urls')),
    path('upload/', include('uploader.urls')),
    path('manif/', include('manifestation.urls')),
    path('work/', include('work.urls')),
    path('audit/', include('audit.urls')),
    path('list/', include('list.urls')),
    path('lang/', include('core.lang_urls')),
    path('user/', include('core.user_urls')),
    path('misc/', include('core.misc_urls')),
    path('catalogue/', include('catalogue.urls')),
    path('suggestions/', include('suggestions.urls')),
]

for url_path, file_path in [
    ('img', media_serv.IMG_PATH),
]:
    urlpatterns += static(urljoin(settings.MEDIA_URL, url_path), document_root=file_path)

urlpatterns += [
    path('file-download/<path:file_path>', core.views.download_file, name='file-download'),
]

work/urls.py
from django.urls import path, re_path

from core.helper import url_serv
from core.views import default_view
from . import views

app_name = 'work'
urlpatterns = [
    re_path('form/corr/(?P<iwork_id>[0-9]+)?\\Z', views.CorrView.as_view(), name='corr_form'),
    re_path('form/dates/(?P<iwork_id>[0-9]+)?\\Z', views.DatesView.as_view(), name='dates_form'),
    re_path('form/places/(?P<iwork_id>[0-9]+)?\\Z', views.PlacesView.as_view(), name='places_form'),
    path('form/manif/<int:iwork_id>', views.ManifView.as_view(), name='manif_init'),
    path('form/manif/<int:iwork_id>/<str:manif_id>', views.ManifView.as_view(), name='manif_update'),
    re_path('form/resources/(?P<iwork_id>[0-9]+)?\\Z', views.ResourcesView.as_view(), name='resources_form'),
    re_path('form/details/(?P<iwork_id>[0-9]+)?\\Z', views.DetailsView.as_view(), name='details_form'),
    path('form/overview/<int:iwork_id>', views.overview_view, name='overview_form'),
]
urlpatterns.extend(
    url_serv.create_common_urls_for_section(
        init_view=views.CorrView.as_view(),
        # edit_view=views.full_form,
        search_view=views.WorkSearchView.as_view(),
        merge_view=default_view,
        edit_id_name='iwork_id',
    )
)

urlpatterns.extend(url_serv.create_urls_for_quick_init(
    views.WorkQuickInitView.as_view(),
    views.return_quick_init,
))

work/views.py
import logging
import re
from collections.abc import Callable
from typing import Iterable, Any, Type

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Q, Model
from django.db.models.lookups import Exact, Lookup
from django.forms import BaseForm
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View

from catalogue.utils import get_user_catalogues
from core import constant
from core.constant import REL_TYPE_COMMENT_AUTHOR, REL_TYPE_COMMENT_ADDRESSEE, REL_TYPE_WORK_IS_REPLY_TO, \
    REL_TYPE_WORK_MATCHES, REL_TYPE_COMMENT_DATE, REL_TYPE_WAS_SENT_FROM, REL_TYPE_COMMENT_ORIGIN, \
    REL_TYPE_COMMENT_DESTINATION, REL_TYPE_WAS_SENT_TO, REL_TYPE_COMMENT_ROUTE, REL_TYPE_FORMERLY_OWNED, \
    REL_TYPE_ENCLOSED_IN, REL_TYPE_COMMENT_RECEIPT_DATE, REL_TYPE_COMMENT_REFERS_TO, REL_TYPE_STORED_IN, \
    REL_TYPE_COMMENT_PERSON_MENTIONED, REL_TYPE_MENTION, REL_TYPE_MENTION_PLACE, \
    REL_TYPE_MENTION_WORK, REL_TYPE_CREATED, REL_TYPE_WAS_ADDRESSED_TO, REL_TYPE_IS_RELATED_TO
from core.export_data import excel_maker, cell_values
from core.forms import WorkRecrefForm, PersonRecrefForm, ManifRecrefForm, CommentForm, LocRecrefForm
from core.helper import view_serv, lang_serv, model_serv, query_serv, renderer_serv, date_serv
from core.helper.common_recref_adapter import RecrefFormAdapter
from core.helper.form_serv import save_multi_rel_recref_formset
from core.helper.lang_serv import LangModelAdapter, NewLangForm
from core.helper.perm_serv import class_permission_required
from core.helper.query_serv import create_recref_lookup_fn
from core.helper.recref_handler import SingleRecrefHandler, RecrefFormsetHandler, SubjectHandler, ImageRecrefHandler, \
    TargetResourceFormsetHandler, MultiRecrefAdapterHandler
from core.helper.recref_serv import create_recref_if_field_exist
from core.helper.renderer_serv import RendererFactory
from core.helper.view_components import DownloadCsvHandler, HeaderValues
from core.helper.view_handler import FullFormHandler
from core.helper.view_serv import DefaultSearchView
from core.models import Recref, CofkLookupCatalogue
from institution import inst_serv
from location import location_serv
from location.models import CofkUnionLocation
from login import utils
from manifestation import manif_serv
from manifestation.manif_serv import create_manif_id
from manifestation.models import CofkUnionManifestation, CofkManifCommentMap, \
    CofkUnionLanguageOfManifestation, CofkManifImageMap
from person import person_serv
from person.models import CofkUnionPerson
from work import work_serv, subqueries
from work.forms import WorkAuthorRecrefForm, WorkAddresseeRecrefForm, \
    AuthorRelationChoices, AddresseeRelationChoices, PlacesForm, DatesForm, CorrForm, ManifForm, \
    ScribeRelationChoices, \
    DetailsForm, CommonWorkForm, manif_type_choices, CompactSearchFieldset, ExpandedSearchFieldset, \
    ManifPersonMRRForm
from work.models import CofkWorkPersonMap, CofkUnionWork, CofkWorkCommentMap, CofkWorkResourceMap, \
    CofkUnionLanguageOfWork
from work.recref_adapter import WorkLocRecrefAdapter, ManifInstRecrefAdapter, WorkSubjectRecrefAdapter, \
    EarlierLetterRecrefAdapter, LaterLetterRecrefAdapter, EnclosureManifRecrefAdapter, EnclosedManifRecrefAdapter, \
    WorkCommentRecrefAdapter, ManifCommentRecrefAdapter, WorkResourceRecrefAdapter, ManifImageRecrefAdapter, \
    WorkPersonRecrefAdapter, ManifPersonRecrefAdapter
from work.view_components import WorkFormDescriptor
from work.work_serv import DisplayableWork

log = logging.getLogger(__name__)


def create_search_fn_person_recref(rel_types: list) -> Callable:
    def _fn(f, v):
        return Q(**{
            'cofkworkpersonmap__person_id': v,
            'cofkworkpersonmap__relationship_type__in': rel_types,
        })

    return _fn


def create_lookup_fn_by_comment(rel_types: list) -> Callable:
    return create_recref_lookup_fn(rel_types, 'cofkworkcommentmap__comment',
                                   query_serv.comment_detail_fields)


def create_lookup_fn_by_resource(rel_types: list) -> Callable:
    return create_recref_lookup_fn(rel_types, 'cofkworkresourcemap__resource',
                                   query_serv.resource_detail_fields)


def lookup_fn_flags(lookup_fn, field_name, value):
    cond_map = [
        (r'Date\s+of\s+work\s+INFERRED', lambda: Q(date_of_work_inferred=1)),
        (r'Date\s+of\s+work\s+UNCERTAIN', lambda: Q(date_of_work_uncertain=1)),
        (r'Date\s+of\s+work\s+APPROXIMATE', lambda: Q(date_of_work_approx=1)),
        (r'Author\s*/\s*sender\s+INFERRED', lambda: Q(authors_inferred=1)),
        (r'Author\s*/\s*sender\s+UNCERTAIN', lambda: Q(authors_uncertain=1)),
        (r'Addressee\s+INFERRED', lambda: Q(addressees_inferred=1)),
        (r'Addressee\s+UNCERTAIN', lambda: Q(addressees_uncertain=1)),
        (r'Origin\s+INFERRED', lambda: Q(origin_inferred=1)),
        (r'Origin\s+UNCERTAIN', lambda: Q(origin_uncertain=1)),
        (r'Destination\s+INFERRED', lambda: Q(destination_inferred=1)),
        (r'Destination\s+UNCERTAIN', lambda: Q(destination_uncertain=1)),
    ]

    query = Q()
    for pattern, q in cond_map:
        if re.search(pattern, value, re.IGNORECASE):
            query |= q()
    return query


def create_search_fn_location_recref(rel_types: list) -> Callable:
    def _fn(f, v):
        return Q(**{
            'cofkworklocationmap__location_id': v,
            'cofkworklocationmap__relationship_type__in': rel_types,
        })

    return _fn


class BasicWorkFFH(FullFormHandler):
    def __init__(self, pk, template_name, *args, request_data=None, request=None, **kwargs):
        self.request_iwork_id = None
        super().__init__(pk, *args,
                         request_data=request_data or None,
                         request=request, **kwargs)
        self.template_name = template_name

        # this variable will be assigned after **valid POST request** saved work
        self.saved_work = None

    def load_data(self, pk, *args, request_data=None, request=None, **kwargs):
        self.request_iwork_id = pk
        if self.request_iwork_id:
            self.work = get_object_or_404(CofkUnionWork, iwork_id=self.request_iwork_id)
        else:
            self.work = None

        self.safe_work = self.work or CofkUnionWork(init_seq_id=False)

        self.common_work_form = CommonWorkForm(request_data, initial={
            'catalogue': self.safe_work.original_catalogue_id,
            'work_to_be_deleted': self.safe_work.work_to_be_deleted,
        })

        catalogue_list = [('', None)] + [(c.catalogue_name, c.catalogue_code) for c in get_user_catalogues(request)]
        self.common_work_form.fields['catalogue_list'].widget.choices = catalogue_list
        self.common_work_form.fields['catalogue'].widget.choices = [(i[1], i[0]) for i in catalogue_list]

    def create_context(self, is_save_success=False):
        context = super().create_context()
        context.update({
                           'iwork_id': self.request_iwork_id
                       } | WorkFormDescriptor(self.work).create_context()
                       | view_serv.create_is_save_success_context(is_save_success)
                       )
        return context

    def render_form(self, request, is_save_success=False):
        return render(request, self.template_name, self.create_context(is_save_success))

    def save_work(self, request, work: CofkUnionWork):
        # ----- save work
        if not work.work_id:
            work.init_seq_id()
            work.work_id = work_serv.create_work_id(work.iwork_id)

        # handle catalogue
        self.common_work_form.is_valid()
        cat_code = self.common_work_form.cleaned_data.get('catalogue')
        if cat_code and work.original_catalogue_id != cat_code:
            log.info('change original_catalogue_id from [{}] to [{}]'.format(
                work.original_catalogue_id, cat_code))
            work.original_catalogue_id = cat_code

        # handle work_to_be_deleted
        work.work_to_be_deleted = self.common_work_form.cleaned_data.get('work_to_be_deleted', 0)

        if work.description != (cur_desc := work_serv.get_recref_display_name(work)):
            work.description = cur_desc

        work.update_current_user_timestamp(request.user.username)
        work.save()
        log.info(f'save work {work}')
        self.saved_work = work

        return work


class PlacesFFH(BasicWorkFFH):
    def __init__(self, pk, *args, request_data=None, request=None, **kwargs):
        super().__init__(pk, 'work/places_form.html', *args,
                         request_data=request_data, request=request, **kwargs)

    def load_data(self, pk, *args, request_data=None, request=None, **kwargs):
        super().load_data(pk, request_data=request_data, request=request)

        self.origin_loc_handler = SingleRecrefHandler(
            form_field_name='selected_origin_location_id',
            rel_type=REL_TYPE_WAS_SENT_FROM,
            create_recref_adapter_fn=WorkLocRecrefAdapter,
        )
        self.destination_loc_handler = SingleRecrefHandler(
            form_field_name='selected_destination_location_id',
            rel_type=REL_TYPE_WAS_SENT_TO,
            create_recref_adapter_fn=WorkLocRecrefAdapter,
        )

        dates_form_initial = (
                {}
                | self.origin_loc_handler.create_init_dict(self.work)
                | self.destination_loc_handler.create_init_dict(self.work)
        )
        self.places_form = PlacesForm(request_data, instance=self.work, initial=dates_form_initial)

        # comments
        self.add_recref_formset_handler(WorkCommentFormsetHandler(
            prefix='origin_comment',
            request_data=request_data,
            form=CommentForm,
            rel_type=REL_TYPE_COMMENT_ORIGIN,

work/templates/work/basic_form.html
{% extends "core/emlo_common_form.html" %}
{% load static %}

{% block head %}
    {{ block.super }}
    <script src="/static/core/js/recref_service.js"></script>
    <script src="{% static 'core/js/ref_publication_service.js' %}" defer></script>
    <script src="{% static 'core/js/selectfilter.js' %}" defer></script>
    <script>
        $(function () {
            setup_selectfilter();
            $('.catalogue-div .selectfilter-root').on('select-changed', function (e, selected_text, selected_val) {
                document.querySelector('#id_catalogue').value = selected_val;
            });
            $('.sf-select').mousedown(function (e) {
                e.preventDefault()
                this.blur()
            });
        });
    </script>
{% endblock %}

{% block content %}

    <div class="form-core-div">
        <div class="form-col-left toc-host"></div>
        <div class="form-col-right">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include "core/component/form_descriptor.html" with descriptor=form_descriptor %}

                <div class="multi_rel_recref_container">
                <label>Original catalogue:</label>
                <div>
                {% if common_work_form %}
                    <div class="catalogue-div">
                        {% include "core/component/selectfilter.html" with select_field=common_work_form.catalogue  datalist_field=common_work_form.catalogue_list %}
                    </div>

                    {% include "core/component/common_checkbox.html" with field=common_work_form.work_to_be_deleted name='Work marked for deletion' is_normal_size=True %}
                {% endif %}
                </div>
                </div>

                <div class="row-no-margin">
                    {% include "work/component/tab_link.html" with name='Correspondents' vname='work:corr_form' iwork_id=iwork_id %}
                    {% include "work/component/tab_link.html" with name='Dates' vname='work:dates_form' iwork_id=iwork_id %}
                    {% include "work/component/tab_link.html" with name='Places' vname='work:places_form' iwork_id=iwork_id %}
                    {% if iwork_id %}
                        {% include "work/component/tab_link.html" with name='Manifestation' vname='work:manif_init' iwork_id=iwork_id %}
                    {% endif %}
                    {% if iwork_id %}
                        {% include "work/component/tab_link.html" with name='Resources' vname='work:resources_form' iwork_id=iwork_id %}
                    {% endif %}
                    {% include "work/component/tab_link.html" with name='Other Details' vname='work:details_form' iwork_id=iwork_id %}
                    {% if iwork_id %}
                        {% include "work/component/tab_link.html" with name='Overview' vname='work:overview_form' iwork_id=iwork_id %}
                    {% endif %}
                </div>


                <div>
                    {% block tabcontent %}
                    {% endblock %}
                </div>
                <div class="bg-white sticky-bottom">
                <hr>
                {% include "core/component/actionbox_form.html" with save_perm=constant.PM_CHANGE_WORK %}
                {% include "core/component/close_if_save_success.html" with is_save_success=is_save_success %}
                </div>


            </form>


        </div>
    </div>





{% endblock %}

work/templates/work/compact_search_table_layout.html
{% load cl_filters work_util_tags %}

<script>
    let tippies = [];

</script>

<table id="results_table">
    <thead>
    <tr></tr>
    <tr>
        <th>Description</th>
        <th>Date for ordering</th>
        <th>&nbsp;</th>
        <th>Images</th>
        <th>Manifestations</th>
        <th>Related resources</th>
        <th>ID</th>
        <th>Last edit</th>
    </tr>
    </thead>
    <tbody>

    {% for r in search_results %}
        <tr class="selectable_entry {% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}" entry_id="{{ r.iwork_id }}">

            <td>
                {% include 'work/component/moreinfo.html' with work=r %}
                {{ r.description }}
            </td>
            <td>
                {{ r.date_for_ordering }}

                {% if r.date_of_work_as_marked %}
                    <p>As marked: {{ r.date_of_work_as_marked }}</p>
                {% endif %}
            </td>
            <td>
                {% if r.work_to_be_deleted|is_general_true %}
                    {% include 'work/component/delete.html' %}
                {% endif %}

                {% include 'work/component/exclamation.html' with work=r %}
            </td>
            <td>
                {% if r.images %}
                    {{ r.images|render_queryable_images }}
                {% endif %}
            </td>

            {% include 'work/component/manif_display_td.html' with work=r %}

            <td>
                {% if r.related_resources %}
                    {{ r.related_resources|display_resources }}
                {% endif %}
            </td>
            <td>
                {% include 'core/component/search_table_layout/link_record.html' with id=r.iwork_id view='work:full_form' %}
            </td>
            <td>
                {{ r.change_timestamp|date:"d M Y H:i" }} by {{ r.change_user }}<br/>
                Source: {{ r.accession_code }}<br/>
                [{{ r.catalogue}}]
            </td>
        </tr>
    {% endfor %}
    </tbody>

</table>

work/templates/work/corr_form.html
{% extends "work/basic_form.html" %}
{% block tabcontent %}
    <div id="header_author" class="header toc-item">
        <h2>Authors / Senders</h2>
    </div>
    <fieldset>
        {% include "core/component/common_multi_rel_recref_formset.html" with multi_rel_recref_formset=author_formset recref_type='person' id_field=corr_form.selected_author_id label_add='Add another author/sender:' %}

        <div class="multi_rel_recref_container">
        <label> Authors/sender as marked: </label>
        {{ corr_form.authors_as_marked }}
        </div>

        <div class="multi_rel_recref_container">
        <label> Issues with authors/senders: </label>

        <div class="row-no-margin">
            <div class="margin-right">
                {% include "core/component/common_checkbox.html" with field=corr_form.authors_inferred name='Authors / senders inferred' is_normal_size=True%}
            </div>


            <div class="margin-right">
                {% include "core/component/common_checkbox.html" with field=corr_form.authors_uncertain  name='Authors / senders uncertain' is_normal_size=True%}
            </div>
        </div>
        </div>

        {% include "core/component/comment_publication_formset.html" with comment_formset=author_comment_formset comment_title='Notes on authors/senders' header_id='header_comment_author' header_class='toc-sub-item' %}
    </fieldset>


    <div id="header_addressees" class="header toc-item">
        <h2>Addressees</h2>
    </div>
    <fieldset>
        {% include "core/component/common_multi_rel_recref_formset.html" with multi_rel_recref_formset=addressee_formset recref_type='person' id_field=corr_form.selected_addressee_id label_add='Add another addressee:' %}

        <div class="multi_rel_recref_container">
        <label> Addressees as marked: </label>
        {{ corr_form.addressees_as_marked }}
        </div>

        <div class="multi_rel_recref_container">
        <label class="name"> Issues with addressees: </label>

        <div class="row-no-margin">
            <div class="margin-right">
                {% include "core/component/common_checkbox.html" with field=corr_form.addressees_inferred name='Addressees inferred' %}
            </div>
            <div class="margin-right">
                {% include "core/component/common_checkbox.html" with field=corr_form.addressees_uncertain  name='Addressees uncertain' %}
            </div>
        </div>
        </div>

        {% include "core/component/comment_publication_formset.html" with comment_formset=addressee_comment_formset comment_title='Notes on addressees' header_id='header_comment_addressee' header_class='toc-sub-item' %}

    </fieldset>

    <div id="header_earlier_letter" class="header toc-item">
        <h2>Earlier letter</h2>
    </div>
    <fieldset>
        {% include "core/component/create_update_recref.html" with recref_type='work' recref_formset=recref_earlier_letter.update_formset new_form=recref_earlier_letter.new_form add_label='Add letter answered by this one:' no_date=True %}
    </fieldset>

    <div id="header_later_letter" class="header toc-item">
        <h2>Later letter</h2>
    </div>
    <fieldset>
        {% include "core/component/create_update_recref.html" with recref_type='work' recref_formset=recref_later_letter.update_formset new_form=recref_later_letter.new_form add_label='Add reply to this:' no_date=True %}
    </fieldset>

    <div id="header_matching" class="header toc-item">
        <h2>Matching letter</h2>
    </div>
    <fieldset>
        {% include "core/component/create_update_recref.html" with recref_type='work' recref_formset=recref_matching_letter.update_formset new_form=recref_matching_letter.new_form add_label='Add another match:' no_date=True %}
    </fieldset>

{% endblock %}

work/templates/work/dates_form.html
{% extends "work/basic_form.html" %}
{% load static %}
{% block tabcontent %}
    <h1>Work - Dates</h1>

    {% include "work/component/common_date_fields.html" with autodate_id='autodate_std' name='work' date_as_marked=dates_form.date_of_work_as_marked calendar_used=dates_form.original_calendar is_range=dates_form.date_of_work_std_is_range day_field=dates_form.date_of_work_std_day month_field=dates_form.date_of_work_std_month year_field=dates_form.date_of_work_std_year day_field2=dates_form.date_of_work2_std_day month_field2=dates_form.date_of_work2_std_month year_field2=dates_form.date_of_work2_std_year normal_date=dates_form.date_of_work_std gregorian_date=dates_form.date_of_work_std_gregorian inferred=dates_form.date_of_work_inferred  uncertain=dates_form.date_of_work_uncertain  approx=dates_form.date_of_work_approx date_comment_formset=date_comment_formset %}


    <script src="{% static 'core/js/auto_date_calendar.js' %}" defer></script>
    <script>
        $(function () {
            setup_autodate_div('#autodate_std');
        })
    </script>

{% endblock %}

work/templates/work/manif_base.html
{% extends "work/basic_form.html" %}
{% load static %}

{% block tabcontent %}
    <h1>Work - Manifestation</h1>
    <div>
        <span>Add new manifestation:</span>
        <a class="btn" href="{% url 'work:manif_init' iwork_id %}">
            New
        </a>
    </div>
    Existing manifestation

    <table>
        <thead>
        <tr>
            <td>Edit</td>
            <td>Del</td>
            <td>Repository</td>
            <td>ID / shelfmark / printed edition</td>
            <td>Document type</td>
            <td>Image</td>
            <td>Further details</td>
        </tr>
        </thead>

        <tbody>
        {% for manif in manif_set %}
            <tr>
                <td>

                    {% if manif_id == manif.manifestation_id %}
                        <strong>Editing --> </strong>
                    {% else %}
                        <a class="btn" href="{% url 'work:manif_update' iwork_id manif.manifestation_id %}">
                            Edit
                        </a>
                    {% endif %}
                </td>
                <td>
                    <input id="del_manif_{{ manif.manifestation_id }}" name="del_manif_id_list" type="checkbox"
                           value="{{ manif.manifestation_id }}"/>
                    <label for="del_manif_{{ manif.manifestation_id }}"></label>
                </td>
                <td>
                    {% if manif.inst_display_name %}
                        {{ manif.inst_display_name }}
                    {% endif %}
                </td>
                <td>
                    {% if manif.id_number_or_shelfmark %}
                        {{ manif.id_number_or_shelfmark }}
                    {% endif %}

                    {% if manif.id_number_or_shelfmark and manif.printed_edition_details %}
                        <br/>
                    {% endif %}

                    {% if manif.printed_edition_details %}
                        {{ manif.printed_edition_details }}
                    {% endif %}

                </td>
                <td> {{ manif.manifestation_type }} </td>
                <td> <!-- KTODO Image --> </td>
                <td>
                    {% if manif.lang_list_str %}
                        <span>Language of this manifestation: </span>
                        {{ manif.lang_list_str }}
                    {% endif %}
                    {% if manif.manifestation_is_translation %}
                        <span>Manifestation is translation.</span>
                    {% endif %}
                </td>
            </tr>

        {% endfor %}

        </tbody>

    </table>



    <div id="form-content">
        {% include "work/component/manif_form.html" %}
    </div>

{% endblock %}

work/templates/work/manif_init.html
{% extends "work/basic_form.html" %}
{% load static %}

{% block tabcontent %}
    <h1>Work - Manifestation</h1>
    <div>
        <span>Add new manifestation:</span>
        <a class="btn" href="{% url 'work:manif_init' iwork_id %}">
            New
        </a>
    </div>
    Existing manifestation  <!-- KTODO -->

    <table>
        <thead>
        <tr>
            <td>Edit</td>
            <td>Del</td>
            <td>Repository</td>
            <td>ID / shelfmark / printed edition</td>
            <td>Document type</td>
            <td>Image</td>
            <td>Further details</td>
        </tr>
        </thead>

        <tbody>
        {% for manif in manif_set %}
            <tr>
                <td>

                    {% if manif_id == manif.manifestation_id %}
                        <strong>Editing --> </strong>
                    {% else %}
                        <a class="btn" href="{% url 'work:manif_update' iwork_id manif.manifestation_id %}">
                            Edit
                        </a>
                    {% endif %}
                </td>
                <td>
                    <input id="del_manif_{{ manif.manifestation_id }}" name="del_manif_id_list" type="checkbox" value="{{ manif.manifestation_id }}" />
                    <label for="del_manif_{{ manif.manifestation_id }}"></label>
                </td>
                <td>
                    {{ manif.inst_display_name }}
                </td>
                <td> {{ manif.id_number_or_shelfmark }} </td>
                <td> {{ manif.manifestation_type }} </td>
                <td> <!-- KTODO Image --> </td>
                <td>
                    {% if manif.lang_list_str %}
                        <span>Language of this manifestation: </span>
                        {{ manif.lang_list_str }}
                    {% endif %}
                    {% if manif.manifestation_is_translation  %}
                        <span>Manifestation is translation.</span>
                    {% endif %}
                </td>
            </tr>

        {% endfor %}

        </tbody>

    </table>



    <div id="form-content">
        {% include "work/component/manif_form.html" %}
    </div>

{% endblock %}

work/templates/work/places_form.html
{% extends "work/basic_form.html" %}
{% block tabcontent %}
    <h1>Work - Places</h1>
    {% include "work/component/place_fieldset.html" with name='origin' marked=places_form.origin_as_marked selected_id=places_form.selected_origin_location_id inferred=places_form.origin_inferred uncertain=places_form.origin_uncertain comment_formset=origin_comment_formset %}
    {% include "work/component/place_fieldset.html" with name='destination' marked=places_form.destination_as_marked selected_id=places_form.selected_destination_location_id inferred=places_form.destination_inferred uncertain=places_form.destination_uncertain comment_formset=destination_comment_formset %}

    <fieldset>
        <legend id="header_route" class="toc-item">Route</legend>
        {% include "core/component/comment_publication_formset.html" with comment_formset=route_comment_formset comment_title='Route from origin to destination' header_id='header_route_comment' header_class='toc-sub-item' %}
    </fieldset>


{% endblock %}