list/urls.py
from django.urls import path

from .views import CatalogueListView, RoleListView, SubjectListView, OrgTypeListView, SavedQueries

app_name = 'list'
urlpatterns = [
    path('subjects/', SubjectListView.as_view(), name='subjects'),
    path('roles/', RoleListView.as_view(), name='roles'),
    path('catalogues/', CatalogueListView.as_view(), name='catalogues'),
    path('orgtypes/', OrgTypeListView.as_view(), name='orgtypes'),
    path('queries/', SavedQueries.as_view(), name='savedqueries')
]

person/urls.py
from core.helper import url_serv
from . import views

app_name = 'person'
urlpatterns = []
urlpatterns.extend(
    url_serv.create_common_urls_for_section(
        init_view=views.PersonInitView.as_view(),
        edit_view=views.full_form,
        delete_view=views.PersonDeleteConfirmView.as_view(),
        search_view=views.PersonSearchView.as_view(),
        merge_view=views.PersonMergeChoiceView.as_view(),
        merge_action_view=views.PersonMergeActionView.as_view(),
        merge_confirm_view=views.PersonMergeConfirmView.as_view(),
        edit_id_name='iperson_id',
    )
)

urlpatterns.extend(url_serv.create_urls_for_quick_init(
    views.PersonQuickInitView.as_view(),
    views.return_quick_init,
))

siteedit2/urls.py
from urllib.parse import urljoin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import core.views
from core.helper import media_serv

urlpatterns = [
    path('', RedirectView.as_view(url='/login/dashboard')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('repositories/', include('institution.urls')),
    path('location/', include('location.urls')),
    path('person/', include('person.urls')),
    path('publication/', include('publication.urls')),
    path('upload/', include('uploader.urls')),
    path('manif/', include('manifestation.urls')),
    path('work/', include('work.urls')),
    path('audit/', include('audit.urls')),
    path('list/', include('list.urls')),
    path('lang/', include('core.lang_urls')),
    path('user/', include('core.user_urls')),
    path('misc/', include('core.misc_urls')),
    path('catalogue/', include('catalogue.urls')),
    path('suggestions/', include('suggestions.urls')),
]

for url_path, file_path in [
    ('img', media_serv.IMG_PATH),
]:
    urlpatterns += static(urljoin(settings.MEDIA_URL, url_path), document_root=file_path)

urlpatterns += [
    path('file-download/<path:file_path>', core.views.download_file, name='file-download'),
]

person/models.py
from django.db import models
from django.utils.safestring import mark_safe

from core.helper import model_serv
from core.helper.model_serv import RecordTracker
from core.models import Recref

SEQ_NAME_COFKUNIONPERSION__IPERSON_ID = 'cofk_union_person_iperson_id_seq'


class CofkUnionPerson(models.Model, RecordTracker):
    person_id = models.CharField(primary_key=True, max_length=100)
    foaf_name = models.CharField(max_length=200)
    skos_altlabel = models.TextField(blank=True, null=True)  # Synonyms
    is_tombstone = models.BooleanField(default=False, help_text="Mark as tombstone instead of deleting")

    """
    'Other versions of name'
    who assign value and use this field ?
    """
    skos_hiddenlabel = models.TextField(blank=True, null=True)
    person_aliases = models.TextField(blank=True, null=True)  # Difference between synonyms and aliases?
    date_of_birth_year = models.IntegerField(blank=True, null=True)
    date_of_birth_month = models.IntegerField(blank=True, null=True)
    date_of_birth_day = models.IntegerField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    date_of_birth_inferred = models.SmallIntegerField(default=0)
    date_of_birth_uncertain = models.SmallIntegerField(default=0)
    date_of_birth_approx = models.SmallIntegerField(default=0)
    date_of_death_year = models.IntegerField(blank=True, null=True)
    date_of_death_month = models.IntegerField(blank=True, null=True)
    date_of_death_day = models.IntegerField(blank=True, null=True)
    date_of_death = models.DateField(blank=True, null=True)
    date_of_death_inferred = models.SmallIntegerField(default=0)
    date_of_death_uncertain = models.SmallIntegerField(default=0)
    date_of_death_approx = models.SmallIntegerField(default=0)
    gender = models.CharField(max_length=1)
    is_organisation = models.CharField(max_length=1)
    iperson_id = models.IntegerField(unique=True, )
    creation_timestamp = models.DateTimeField(blank=True, null=True, default=model_serv.default_current_timestamp)
    creation_user = models.CharField(max_length=50)
    change_timestamp = models.DateTimeField(blank=True, null=True, default=model_serv.default_current_timestamp)
    change_user = models.CharField(max_length=50)
    editors_notes = models.TextField(blank=True, null=True)
    further_reading = models.TextField(blank=True, null=True)
    organisation_type = models.ForeignKey('core.CofkUnionOrgType', models.DO_NOTHING, db_column='organisation_type',
                                          blank=True, null=True, related_name='person')
    date_of_birth_calendar = models.CharField(max_length=2)
    date_of_birth_is_range = models.SmallIntegerField(default=0)
    date_of_birth2_year = models.IntegerField(blank=True, null=True)
    date_of_birth2_month = models.IntegerField(blank=True, null=True)
    date_of_birth2_day = models.IntegerField(blank=True, null=True)
    date_of_death_calendar = models.CharField(max_length=2)
    date_of_death_is_range = models.SmallIntegerField(default=0)
    date_of_death2_year = models.IntegerField(blank=True, null=True)
    date_of_death2_month = models.IntegerField(blank=True, null=True)
    date_of_death2_day = models.IntegerField(blank=True, null=True)
    flourished = models.DateField(blank=True, null=True)
    flourished_calendar = models.CharField(max_length=2)
    flourished_is_range = models.SmallIntegerField(default=0)
    flourished_year = models.IntegerField(blank=True, null=True)
    flourished_month = models.IntegerField(blank=True, null=True)
    flourished_day = models.IntegerField(blank=True, null=True)
    flourished2_year = models.IntegerField(blank=True, null=True)
    flourished2_month = models.IntegerField(blank=True, null=True)
    flourished2_day = models.IntegerField(blank=True, null=True)
    uuid = models.UUIDField(blank=True, null=True)
    flourished_inferred = models.SmallIntegerField(default=0)
    flourished_uncertain = models.SmallIntegerField(default=0)
    flourished_approx = models.SmallIntegerField(default=0)
    locations = models.ManyToManyField(to='location.CofkUnionLocation',
                                       through='person.CofkPersonLocationMap',
                                       through_fields=('person', 'location'))
    images = models.ManyToManyField(to='core.CofkUnionImage',
                                    through='CofkPersonImageMap')
    resources = models.ManyToManyField(to='core.CofkUnionResource',
                                       through='CofkPersonResourceMap')
    comments = models.ManyToManyField(to='core.CofkUnionComment',
                                      through='CofkPersonCommentMap')
    works = models.ManyToManyField(to='work.CofkUnionWork',
                                   through='work.CofkWorkPersonMap')
    roles = models.ManyToManyField(to='core.CofkUnionRoleCategory',
                                   through='CofkPersonRoleMap', related_name='person')

    # related_people = models.ManyToManyField(to='CofkUnionPerson',
    #                                        through='CofkPersonPersonMap',
    #                                        through_fields=('person', 'related'))

    @property
    def names_and_roles(self) -> str:
        from person import person_serv
        names_and_roles = ''.join(f'<p>{s}</p>' for s in person_serv.get_name_details(self))
        return mark_safe(names_and_roles)

    def to_string(self, is_details=False) -> str:
        """
        Used by work.creators_for_display and work.addressees_for_display
        """
        dob = str(self.date_of_birth_year)
        dod = str(self.date_of_death_year)

        if self.date_of_death_is_range == 1:
            dod += ' or after'

        if self.date_of_birth_is_range == 1:
            dob += ' or before'

        if self.date_of_birth_year and self.date_of_death_year:
            person = f'{self.foaf_name}, {dob}-{dod}'
        elif self.date_of_birth_year:
            person = f'{self.foaf_name} b. {dob}'
        elif self.date_of_death_year:
            person = f'{self.foaf_name} d. {dod}'
        else:
            person = str(self.foaf_name)

        if not is_details:
            return person

        if self.skos_altlabel:
            person += f', also known as: {self.skos_altlabel}'

        if self.person_aliases:
            person += f' (titles/roles: {self.person_aliases}'

        return person

    class Meta:
        db_table = 'cofk_union_person'
        permissions = [
            ('export_file', 'Export csv/excel from search results'),
        ]

    def __init__(self, *args, init_seq_id=False, **kwargs):
        super().__init__(*args, **kwargs)
        if init_seq_id:
            self.init_seq_id()

    def init_seq_id(self):
        if self.iperson_id is None:
            self.iperson_id = model_serv.next_seq_safe(SEQ_NAME_COFKUNIONPERSION__IPERSON_ID)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.init_seq_id()
        super().save(force_insert, force_update, using, update_fields)


class CofkPersonLocationMap(Recref):
    person = models.ForeignKey(CofkUnionPerson, on_delete=models.CASCADE)
    location = models.ForeignKey('location.CofkUnionLocation', on_delete=models.CASCADE)

    class Meta(Recref.Meta):
        db_table = 'cofk_person_location_map'
        indexes = [
            models.Index(fields=['person', 'relationship_type']),
        ]


class CofkPersonPersonMap(Recref):
    person = models.ForeignKey(CofkUnionPerson,
                               related_name='active_relationships',
                               on_delete=models.CASCADE)
    related = models.ForeignKey(CofkUnionPerson,
                                related_name='passive_relationships',
                                on_delete=models.CASCADE)

    class Meta(Recref.Meta):
        db_table = 'cofk_person_person_map'
        indexes = [
            models.Index(fields=['person', 'relationship_type']),
            models.Index(fields=['related', 'relationship_type']),
        ]


class CofkPersonCommentMap(Recref):
    person = models.ForeignKey(CofkUnionPerson, on_delete=models.CASCADE)
    comment = models.ForeignKey('core.CofkUnionComment', on_delete=models.CASCADE)

    class Meta(Recref.Meta):
        db_table = 'cofk_person_comment_map'
        indexes = [
            models.Index(fields=['person', 'relationship_type']),
        ]


class CofkPersonResourceMap(Recref):
    person = models.ForeignKey(CofkUnionPerson, on_delete=models.CASCADE)
    resource = models.ForeignKey('core.CofkUnionResource', on_delete=models.CASCADE)

    class Meta(Recref.Meta):
        db_table = 'cofk_person_resource_map'
        indexes = [
            models.Index(fields=['person', 'relationship_type']),
        ]


class CofkPersonImageMap(Recref):
    person = models.ForeignKey(CofkUnionPerson, on_delete=models.CASCADE)
    image = models.ForeignKey('core.CofkUnionImage', on_delete=models.CASCADE)

    class Meta(Recref.Meta):
        db_table = 'cofk_person_image_map'
        indexes = [
            models.Index(fields=['person', 'relationship_type']),
        ]


class CofkPersonRoleMap(Recref):
    person = models.ForeignKey(CofkUnionPerson, on_delete=models.CASCADE)
    role = models.ForeignKey('core.CofkUnionRoleCategory', on_delete=models.CASCADE)

    class Meta(Recref.Meta):
        db_table = 'cofk_person_role_map'
        indexes = [
            models.Index(fields=['person', 'relationship_type']),
        ]


def create_person_id(iperson_id) -> str:
    return f'cofk_union_person-iperson_id:{iperson_id}'

person/templates/person/component/date_fields.html
<fieldset class="date-fields-div">
    <legend>{{ title_name | title }}</legend>
    <div class="margin-bottom">
        {% include "core/component/common_form_choices.html" with label_text='Calendar of '|add:title_name choices_field=calendar %}
    </div>
    <div class="is-range-div margin-bottom">
        {{ is_range }}
        <label for="{{ is_range.id_for_label }}">Date range?</label>
        <small>
            {{ date_range_msg }}
        </small>
    </div>

    <div class="margin-bottom">
        <div class="row-no-margin">
            <div class="from-div">
                <label class="from-label">Date:</label>
                {% include 'core/component/form_three_date_fields.html' with day_field=day_field month_field=month_field year_field=year_field %}
            </div>

            <div class="to-div">
                <label class="to-label">To:</label>
                {% include 'core/component/form_three_date_fields.html' with day_field=day_field2 month_field=month_field2 year_field=year_field2 %}
            </div>
        </div>

    </div>

    {% include "person/component/issues_with_date.html" with title='Issues with '|add:title_name|add:':' inferred=inferred  uncertain=uncertain  approx=approx %}

</fieldset>

person/templates/person/component/issues_with_date.html
<div class="margin-bottom">
    <label>{{ title }}</label>
    <div class="issues-date-ct">
        <div class="issues-date-item">
            {{ inferred }}
            <label for="{{ inferred.id_for_label }}">
                <small> Date is inferred </small>
            </label>
        </div>
        <div class="issues-date-item">
            {{ uncertain }}
            <label for="{{ uncertain.id_for_label }}">
                <small> Date is uncertain </small>
            </label>
        </div>
        <div class="issues-date-item">
            {{ approx }}
            <label for="{{ approx.id_for_label }}">
                <small> Date is approximate </small>
            </label>
        </div>
    </div>
</div>

person/templates/person/component/person_search_fieldset.html
{% extends "core/component/search_fieldset/fieldset.html" %}

{% block fields %}

    <!-- Name -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.names_and_titles field_lookup=form.names_and_titles_lookup %}

    {% include "core/component/search_fieldset/from_to_year.html" with title='Born year' from_field=form.birth_year_from to_field=form.birth_year_to field_info=form.birth_year_info %}
    {% include "core/component/search_fieldset/from_to_year.html" with title='Died year' from_field=form.death_year_from to_field=form.death_year_to field_info=form.death_year_info %}
    {% include "core/component/search_fieldset/from_to_year.html" with title='Flourished year' from_field=form.flourished_year_from to_field=form.flourished_year_to field_info=form.flourished_info %}

    {% include "core/component/common_field_layout.html" with field=form.gender %}

    <!-- Person or group -->
    {% include "core/component/common_field_layout.html" with field=form.person_or_group %}

    <!-- Type of group -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.organisation_type field_lookup=form.organisation_type_lookup %}

    <!-- Sent -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.sent field_lookup=form.sent_lookup %}

    <!-- Rec'd -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.recd field_lookup=form.recd_lookup %}

    <!-- Sent and rec'd -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.all_works field_lookup=form.all_works_lookup %}

    <!-- Mentioned -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.mentioned field_lookup=form.mentioned_lookup %}

    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.roles field_lookup=form.roles_lookup %}

    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.editors_notes field_lookup=form.editors_notes_lookup %}

    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.further_reading field_lookup=form.further_reading_lookup %}

    <!-- Images -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.images field_lookup=form.images_lookup %}

    <!-- Other details -->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.other_details field_lookup=form.other_details_lookup %}

    <!-- Last edit -->
    {% include "core/component/search_fieldset/from_to_year.html" with title='Last edit' from_field=form.change_timestamp_from to_field=form.change_timestamp_to field_info=form.change_timestamp_info %}

    <!-- Last changed by-->
    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.change_user field_lookup=form.change_user_lookup %}

    {% include "core/component/search_fieldset/field_with_lookup.html" with field=form.iperson_id field_lookup=form.iperson_id_lookup %}

    <!-- Tombstone -->
    {% include "core/component/search_fieldset/zero_one_checkbox.html" with field=form.include_tombstone %}
    <script>
        var roles_autocomplete = [{% for role in form.role_category_names %}"{{ role|safe }}", {% endfor %}];

        $( "#id_roles" ).autocomplete({
            source: roles_autocomplete,
            minLength: 0,
            appendTo: '#query-fieldset'
        });

        // Search all values on select
        $( "#id_roles" ).on("click", function()    {
            $(this).autocomplete('search', '');
        });

        var org_types_autocomplete = [{% for orgtype in form.org_types %}"{{ orgtype|safe }}", {% endfor %}];

        $( "#id_organisation_type" ).autocomplete({
            source: org_types_autocomplete,
            minLength: 0,
            appendTo: '#query-fieldset'
        });

        // Search all values on select
        $( "#id_organisation_type" ).on("click", function()    {
            $(this).autocomplete('search', '');
        });

    </script>

{% endblock %}