audit/urls.py
from . import views
from django.urls import path

app_name = 'audit'
urlpatterns = [
    path('search', views.AuditSearchView.as_view(), name='search'),
]

catalogue/urls.py
from core.helper import url_serv

from . import views
from list.views import CatalogueListView

app_name = 'catalogue'

urlpatterns = url_serv.create_common_urls_for_section(
    init_view=views.update_catalogue,
    edit_view=views.update_catalogue,
    search_view=views.CatalogueSearchView.as_view(),
)

list/urls.py
from django.urls import path

from .views import CatalogueListView, RoleListView, SubjectListView, OrgTypeListView, SavedQueries

app_name = 'list'
urlpatterns = [
    path('subjects/', SubjectListView.as_view(), name='subjects'),
    path('roles/', RoleListView.as_view(), name='roles'),
    path('catalogues/', CatalogueListView.as_view(), name='catalogues'),
    path('orgtypes/', OrgTypeListView.as_view(), name='orgtypes'),
    path('queries/', SavedQueries.as_view(), name='savedqueries')
]

login/urls.py
from django.contrib.auth.views import logout_then_login, PasswordChangeView
from django.urls import path

from . import views
from .views import EmloLoginView, password_changed

app_name = 'login'
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('gate', EmloLoginView.as_view(), name='gate'),
    path('change-password', PasswordChangeView.as_view(template_name='login/change-password.html',
                                      success_url='password-changed'), name='change-password'),
    path('password-changed', password_changed, name='password-changed'),
    path('logout', logout_then_login, name='logout'),
]

siteedit2/urls.py
from urllib.parse import urljoin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import core.views
from core.helper import media_serv

urlpatterns = [
    path('', RedirectView.as_view(url='/login/dashboard')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('repositories/', include('institution.urls')),
    path('location/', include('location.urls')),
    path('person/', include('person.urls')),
    path('publication/', include('publication.urls')),
    path('upload/', include('uploader.urls')),
    path('manif/', include('manifestation.urls')),
    path('work/', include('work.urls')),
    path('audit/', include('audit.urls')),
    path('list/', include('list.urls')),
    path('lang/', include('core.lang_urls')),
    path('user/', include('core.user_urls')),
    path('misc/', include('core.misc_urls')),
    path('catalogue/', include('catalogue.urls')),
    path('suggestions/', include('suggestions.urls')),
]

for url_path, file_path in [
    ('img', media_serv.IMG_PATH),
]:
    urlpatterns += static(urljoin(settings.MEDIA_URL, url_path), document_root=file_path)

urlpatterns += [
    path('file-download/<path:file_path>', core.views.download_file, name='file-download'),
]

uploader/urls.py
from django.urls import path
from . import views


app_name = 'uploader'

urlpatterns = [
    path('', views.UploadView.as_view(), name='upload_list'),
    path('add', views.AddUploadView.as_view(), name='upload_add'),
    path('<int:upload_id>/', views.upload_review, name='upload_review'),
    path('works', views.ColWorkSearchView.as_view(), name='upload_works')

]

core/forms.py
from django import forms
from django.conf import settings
from django.forms import ModelForm, HiddenInput, IntegerField, Form
from django.urls import reverse

from core.helper import form_serv, model_serv
from core.helper import widgets_serv
from core.helper.form_serv import CommonTextareaField, ZeroOneCheckboxField
from core.models import CofkUnionComment, CofkUnionResource, CofkUnionImage, CofkLookupCatalogue, CofkUnionRoleCategory, \
    CofkUnionSubject, CofkUnionOrgType
from login.models import CofkUser
from login import utils
from manifestation.models import CofkUnionManifestation
from person import person_serv
from work import work_serv


class RecrefForm(forms.Form):
    recref_id = forms.CharField(required=False, widget=forms.HiddenInput())
    target_id = forms.CharField(required=False, widget=forms.HiddenInput())
    rec_name = forms.CharField(required=False)
    from_date = forms.DateField(required=False, widget=widgets_serv.NewDateInput())
    to_date = forms.DateField(required=False, widget=widgets_serv.NewDateInput())
    is_delete = form_serv.DeleteCheckboxField()

    @property
    def target_url(self) -> str:
        return ''  # tobe define by subclass


class PersonRecrefForm(RecrefForm):
    @property
    def target_url(self) -> str:
        return person_serv.get_checked_form_url_by_pk(self.initial.get('target_id'))


class LocRecrefForm(RecrefForm):
    @property
    def target_url(self) -> str:
        return reverse('location:full_form', args=[self.initial.get('target_id')])


class WorkRecrefForm(RecrefForm):
    @property
    def target_url(self) -> str:
        return work_serv.get_checked_form_url_by_pk(self.initial.get('target_id'))


class ManifRecrefForm(RecrefForm):

    @property
    def target_url(self) -> str:
        manif_id = self.initial.get('target_id')
        if not manif_id:
            return ''

        manif: CofkUnionManifestation = model_serv.get_safe(CofkUnionManifestation, pk=manif_id)
        if not manif:
            return ''

        return reverse('work:manif_update', args=[manif.work.iwork_id, manif_id])


class CommentForm(ModelForm):
    comment_id = IntegerField(required=False, widget=HiddenInput())

    record_tracker_label = form_serv.record_tracker_label_fn_factory('Note')

    comment = form_serv.CommonTextareaField(required=True)

    is_delete = form_serv.DeleteCheckboxField()

    class Meta:
        model = CofkUnionComment
        fields = (
            'comment_id',
            'comment',
        )
        labels = {
            'comment': 'Note',
        }


class ResourceForm(ModelForm):
    resource_id = IntegerField(required=False, widget=HiddenInput())
    resource_url = forms.CharField(required=True,
                                   label='URL')
    resource_url.widget.attrs.update({'class': 'url_checker'})

    resource_name = forms.CharField(required=True,
                                    label='Title or brief description',
                                    widget=forms.TextInput(
                                        {'class': 'res_standtext'}
                                    ), )

    resource_details = CommonTextareaField(required=False, label='Further details of resource')
    resource_details.widget.attrs.update({'class': 'res_standtext'})

    record_tracker_label = form_serv.record_tracker_label_fn_factory('Entry')

    is_delete = ZeroOneCheckboxField(is_str=False, label='Delete')
    is_delete.widget.attrs.update({'class': 'warn-checked'})

    class Meta:
        model = CofkUnionResource
        fields = (
            # upload_id = models.OneToOneField("uploader.CofkCollectUpload", null=False, on_delete=models.DO_NOTHING)
            'resource_id',
            'resource_name',
            'resource_url',
            'resource_details',
        )


class ImageForm(ModelForm):
    image_id = IntegerField(required=False, widget=HiddenInput())
    image_filename = forms.CharField(required=False,
                                     label='URL for full-size image')
    image_filename.widget.attrs.update({'class': 'url_checker'})

    thumbnail = forms.CharField(required=False,
                                label='URL for thumbnail (if any)')
    credits = forms.CharField(required=False,
                              label="Credits for 'front end' display*")
    licence_details = form_serv.CommonTextareaField(label='Either: full text of licence*')

    licence_url = forms.CharField(required=False,
                                  label='licence URL*',
                                  initial=settings.DEFAULT_IMG_LICENCE_URL,
                                  )
    licence_url.widget.attrs.update({'class': 'url_checker', })

    can_be_displayed = form_serv.ZeroOneCheckboxField(required=False,
                                                       label='Can be displayed to public',
                                                       initial='1', )
    display_order = forms.IntegerField(required=False, label='Order for display in front end', initial=1)

    def clean_display_order(self):
        display_order = self.cleaned_data.get('display_order')
        try:
            return int(display_order)
        except:
            raise forms.ValidationError('Display order must be an integer')

    class Meta:
        model = CofkUnionImage
        fields = (
            'image_id',
            'image_filename',
            'thumbnail',
            'credits',
            'licence_details',
            'licence_url',
            'can_be_displayed',
            'display_order',
        )


class UploadImageForm(Form):
    selected_image = forms.ImageField(required=False)


class CatalogueForm(ModelForm):
    catalogue_name = forms.CharField(label="Description")
    catalogue_code = forms.CharField(label="Code")
    publish_status = form_serv.ZeroOneCheckboxField(required=False, label='Publish', initial='1', )
    owner = forms.ModelChoiceField(
        label="Owner",
        queryset=utils.get_contributing_editors(),
        widget=forms.Select(attrs={
            'class': 'form-control'
        }),
        empty_label="Select Owner"  # placeholder
    )

    class Meta:
        model = CofkLookupCatalogue
        fields = '__all__'


class RoleForm(ModelForm):
    role_category_desc = forms.CharField(label="Description")

    class Meta:
        model = CofkUnionRoleCategory
        fields = '__all__'


class SubjectForm(ModelForm):
    subject_desc = forms.CharField(label="Description")

    class Meta:
        model = CofkUnionSubject
        fields = '__all__'


class OrgTypeForm(ModelForm):
    org_type_desc = forms.CharField(label="Description")

    class Meta:
        model = CofkUnionOrgType
        fields = '__all__'

core/views.py
from django.http import FileResponse

from core.helper import media_serv
from login.views import dashboard

default_view = dashboard


def download_file(request, file_path):
    real_file_path = media_serv.FILE_DOWNLOAD_PATH.joinpath(file_path).resolve()
    if not real_file_path.as_posix().startswith(media_serv.FILE_DOWNLOAD_PATH.as_posix()):
        raise ValueError('Invalid path')

    response = FileResponse(real_file_path.open('rb'),
                            as_attachment=True,
                            filename=real_file_path.name)
    response['Content-Type'] = 'application/force-download'
    response['Content-Disposition'] = f'attachment; filename={real_file_path.name}'
    return response

core/templates/core/basic_search_page.html
{% extends "core/emlo_logined.html" %}
{% load static cl_filters %}
{% block content %}

    <div class="col col--1of3 align-center">
        <div class="row">
            <h1> {{ title }} </h1>
            {% if add_entry_url and add_entry_url_permission in perms%}
                <div class="margin-left margin-top">
                    <a href="{{ add_entry_url }}" class="btn" target="_blank">Add +</a>
                </div>
            {% endif %}
        </div>
    </div>

    {% include "core/component/messages.html" %}

    <div id="user_messages">
        {% for to_user_msg in to_user_messages %}
            <h1>{{ to_user_msg }}</h1>
        {% endfor %}
    </div>

    <input id="num_records" type="hidden" value="{{ paginator.count }}"/>

    <form id="search_form" method="get">

        <input type="hidden" name="recref_mode" value="{{ recref_mode }}"/>

        <div class="row">

            <!-- Query fieldsets -->
        {% if query_fieldset_list %}
            <aside id="query-fieldset" class="col col--1of4">
                <h3 class="sr-only">Search</h3>
                {% for query_fieldset in query_fieldset_list %}
                    {{ query_fieldset }}
                {% endfor %}

                {% include "core/component/actionbox_search.html" %}
            </aside>
        {% endif %}

            <div id="query-result" class="col col--3of4">

                <!-- Number of results -->
                <div class="col">
                    <div class="result_count">

                        {% if paginator.count > 0 %}
                        <h2>
                            {{ page_obj|get_results_on_page }} out
                            of {{ paginator.count | floatformat:'g' }} {{ paginator.count|pluralize:entity }}
                        </h2>
                        {% endif %}

                    </div>

                    <!-- Show search criteria -->
                    {% if simplified_query %}
                        {% include "core/component/simplified_query.html" with simpliefied_query=simplified_query %}
                    {% endif %}

                </div>

                {% if query_fieldset_list %}
                <!-- Search components (e.g. sort by, records per page) -->
                {{ search_components }}
                {% endif %}

                {% if paginator.count == 0 %}
                    <h2>No results</h2>

                {% else %}
                    <!-- Upper pagination -->
                    {% include 'core/component/pagination.html' %}

                    <!-- search function toolbar (e.g. download output, compact, expanded)  -->
                    <aside class="margin-bottom row">
                        <div class="col col--1of2">
                            {% if query_fieldset_list and paginator.count %}
                                <button id="fieldset-toggle-btn" class="search-form-btn" type="button">
                                    Toggle <span data-feather="search" aria-hidden="true"></span>
                                </button>

                                <button id="save-query-btn" class="search-form-btn" type="submit"
                                        name="__form_action" value="save_query">
                                    Save query <span data-feather="save" aria-hidden="true"></span>
                                </button>
                            {% endif %}

                            {% if can_export_csv %}
                                <button type='submit' class="search-form-btn"
                                        name="__form_action" value="download_csv">
                                    CSV output
                                </button>
                            {% endif %}

                            {% if can_export_excel %}
                                <button id="export_excel_btn" type='submit' class="search-form-btn"
                                        name="__form_action" value="download_excel">
                                    Excel output
                                </button>
                            {% endif %}

                            {% if merge_page_url %}
                                <button class="search-form-btn selectable_mode_btn">
                                    Select
                                </button>
                                <button id="merge_btn" class="search-form-btn" style="display: none">
                                    Merge
                                </button>
                            {% endif %}
                        </div>
                        {# Only display search rendering selection for work #}
                        {% if entity|first in 'work' %}
                            <div class="col col--1of2">
                                <h3 class="sr-only">Layout</h3>
                                <div class="align-right">
                                    <input type="radio" id="display-as-grid" value="grid"
                                           name="display-style"
                                           class="searchcontrol"
                                            {% if is_compact_layout %}
                                           checked
                                            {% endif %}

                                    />
                                    <label for="display-as-grid">
                                        Compact
                                        <small> <span data-feather="grid" aria-hidden="true"></span> </small>
                                    </label>

                                    <input type="radio" id="display-as-list" value="table"
                                           name="display-style"
                                           class="searchcontrol"
                                            {% if not is_compact_layout %}
                                           checked
                                            {% endif %}
                                    />
                                    <label for="display-as-list">
                                        Expanded
                                        <small><span data-feather="list" aria-hidden="true"></span></small>
                                    </label>
                                </div>
                            </div>
                        {% endif %}
                    </aside>

                    {{ results_renderer | safe }}

                    <!-- Lower pagination -->
                    {% include 'core/component/pagination.html' %}

                {% endif %}

            </div>

        </div>

    </form>

    {% if paginator.count > 0 %}
        {% include 'core/component/scroll_to_top.html' %}
    {% endif %}

    {% if merge_page_url %}
        <form id="merge_form" action="{{ merge_page_url }}"></form>
    {% endif %}

    <!-- script -->
    <script>

        let entity = "{{ entity }}".split(',')[0];
        let return_quick_init_vname = "{{ return_quick_init_vname }}";
        {%  if return_quick_init_vname %}
            let vname_action_url = "{% url return_quick_init_vname '__entry_id__' %}";
        {% endif %}
        let recref_mode = "{{ recref_mode }}";

        $('#export_excel_btn').click(function (e) {
            let msg = 'Are you sure you want to export the search results to Excel?'
            let num_records = $('#num_records').val()
            if (num_records) {
                msg = `Are you sure you want to export ${num_records} search results to Excel?`
            }

            if (!confirm(msg)) {
                e.preventDefault();
                return;
            }
        });


        window.on_form_completed = function (data) {
            /*
            this is for button 'Save and Close',
            form page in new tab can all this function to reload the search page
             */
            location.reload()
        }
        $('.open-link-btn').each(function (index, ele) {
            let btn_jqe = $(ele);
            btn_jqe.mousedown(function (e) {
                e.preventDefault()
                let url = btn_jqe.attr('url');
                if (!url) {
                    console.log(`url[${url}] not found in element -- ${ele}`)
                    return;
                }
                window.open(url).focus();
            });
        });

    </script>
    <script src="{% static 'core/js/search-results.js' %}"></script>

{% endblock %}

core/templates/core/delete_confirm.html
{% extends "core/emlo_logined.html" %}

{% block content %}
    <h1>Delete {{ name }}</h1>
    <form method="post">
        {% csrf_token %}

        <h4>{{ name | capfirst }} to be deleted:</h4>
        <div class="margin-bottom">
            {% for obj_desc in obj_desc_list %}
                <div>
                    {{ obj_desc }}
                </div>

            {% endfor %}
        </div>

        <div class="del-confirm-div">
            <h4>To delete, first tick the 'Confirm Deletion' checkbox then click the 'Delete' button. </h4>
            <input type="checkbox" id="confirm-box">
            <label id="confirm-label" for="confirm-box" class="control">
                Tick to confirm deletion of this {{ name }}
            </label>

            <div class="row-no-margin">
                <a id="cancel-btn" class="margin-right btn" href="{{ cancel_url }}"> Cancel </a>
                <button id="del-btn" disabled>Delete</button>
            </div>

        </div>

    </form>


    <script>
        $(() => {
            // event for enable del_btn if check confirm-box is checked
            $('#confirm-box').on('change', function () {
                $('#del-btn').prop('disabled', !$(this).is(':checked'));
            });
        })
    </script>



{% endblock %}

core/templates/core/demo_compact_item.html
<article class="row selectable_entry" entry_id="{{ record.pk }}">
    <div class="col col--4of6">
        <h3>
            <a href="#!">
                {{ record.pk }}
            </a>
        </h3>
        <p><small><a href="#!" class="record_delete">Delete record</a></small></p>
    </div>

    <aside class="col col--2of6 align-right">
        <dl>

            <dt>Last edited by </dt>
            <dd>
                {{ record.change_user }}<br/>
                {{ record.change_timestamp }}
            </dd>
        </dl>
    </aside>
</article>

core/templates/core/demo_search_table_layout.html
<table>
    <thead>
    <tr></tr>
    <tr></tr>
    </thead>
    <tbody>

    {% for r in search_results %}
        <tr class="selectable_entry" entry_id="{{ r.pk }}">
            <td>
                {{ r }}
            </td>
        </tr>
    {% endfor %}
    </tbody>

</table>

core/templates/core/emlo_base.html
{% load static %}
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Union Catalogue Editing Interface: Main menu</title>

    <link href="{% sass_src 'core/scss/main.scss' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'core/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'core/js/jquery-ui.js' %}"></script>
    <script src="{% static 'core/js/emlo-io.js' %}"></script>

    <!-- feature icon -->
    <script src="https://unpkg.com/feather-icons"></script>

    {% block head %}
    {% endblock %}

</head>
<body>

<header class="bg-midnight sticky page-header site-header">
    <div class="header-container">
        <div class="brand-logo">
            <a href="/">
                <img src="/static/core/img/cofk_logo_inverted.png" id="logo" alt="Logo">
            </a>
        </div>
        <div class="col_header">
            {% block header %}
            {% endblock %}
        </div>
    </div>
</header>

{% block content %}
{% endblock %}


{% include "core/footer.html" %}

<script>
    var emlojs = emlojs || {}


    <!-- feature icon -->
    feather.replace()
</script>

<!-- Tooltip  -->
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>

<script>

    t = tippy('[data-tippy-content]',
     {  placement: 'top-start',
        appendTo: document.body,
        allowHTML: true,
        interactive: true });

</script>

</body>
</html>

core/templates/core/emlo_common_form.html
{% extends "core/emlo_logined.html" %}
{% load static %}

{% block head %}
    {{ block.super }}
    <script src="{% static 'core/js/table_of_content_service.js' %}" defer></script>
    <script src="{% static 'core/js/leave_warning.js' %}" defer></script>
    <script>
        $(function () {
            setup_table_of_content();
            emlojs.leave_warning.setup_leave_warning();
        });
    </script>
{% endblock %}

core/templates/core/emlo_logined.html
{% extends "core/emlo_base.html" %}
{% load static %}
{% load cl_filters %}

{% block header %}
    <nav class="flex-space-between">
        <ul class="no-padding no-margin">

            <li class="menu-item">
                <a href="/"><img src="{% static 'core/img/cofk_logo_inverted.png' %}" id="logo"></a>
            </li>

            {% include "core/component/common_section_search_menu.html" %}
            {% include "core/component/common_section_new_menu.html" %}

            {%  if constant.PM_VIEW_SUGGESTIONS in perms %}
            <li class="menu-item">
                    <a href="{% url 'suggestions:suggestion_all' %}" title="Make a suggestion" target="_self" >Suggestions</a>
            </li>
            {% endif %}

            {% if constant.PM_VIEW_LOOKUPCAT in perms %}
                <li class="menu-item">
                    <a href="">Lists</a>
                    <ul class='unstyled-list no-margin menu-subitem'>
                        {%  if constant.PM_CHANGE_ROLECAT in perms %}
                        <a href="{% url 'list:roles' %}">
                            <li>Roles</li>
                        </a>
                        {% endif %}
                        {%  if constant.PM_VIEW_LOOKUPCAT in perms %}
                        <a href="{% url 'catalogue:search' %}">
                            <li>Catalogues</li>
                        </a>
                        {% endif %}
                        {%  if constant.PM_CHANGE_SUBJECT in perms %}
                        <a href="{% url 'list:subjects' %}">
                            <li>Subjects</li>
                        </a>
                        {% endif %}
                        {%  if constant.PM_CHANGE_ORGTYPE in perms %}
                        <a href="{% url 'list:orgtypes' %}">
                            <li>Org. types</li>
                        </a>
                        {% endif %}
                        {%  if constant.PM_CHANGE_ROLECAT in perms %}
                        <a href="{% url 'lang:search' %}">
                            <li>Language</li>
                        </a>
                        {% endif %}
                        {% if constant.PM_CHANGE_USER|can_show_for_perm:perms %}
                        <a href="{% url 'user:search' %}">
                            <li>User</li>
                        </a>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}
        </ul>
        <ul class="no-margin">
            {% if constant.PM_CHANGE_COLLECTWORK|can_show_for_perm:perms %}
                <li class="menu-item">
                    <a href="">Uploads</a>
                    <ul class='unstyled-list no-margin menu-subitem'>
                        <a href="{% url 'uploader:upload_add' %}">
                            <li>Add a new upload</li>
                        </a>
                        <a href="{% url 'uploader:upload_list' %}">
                            <li>Browse uploads</li>
                        </a>
                        <a href="{% url 'uploader:upload_works' %}">
                            <li>Uploaded works</li>
                        </a>
                    </ul>
                </li>
            {% endif %}
            {% if constant.PM_VIEW_AUDIT|can_show_for_perm:perms %}
                <li class="menu-item">
                    <a href="{% url 'audit:search' %}">Audit</a>
                </li>
            {% endif %}
            <li class="menu-item">
                <a href="#!">{{ request.user }}</a>
                <ul class='unstyled-list no-margin menu-subitem' style="left: -100px;">
                    {% if request.user.has_saved_queries %}
                        <a href="{% url 'list:savedqueries' %}">
                            <li>Saved queries</li>
                        </a>
                    {% endif %}
                    <a href="{% url 'login:change-password' %}">
                        <li>Change password</li>
                    </a>
                    <a href="{% url 'login:logout' %}">
                        <li>Logout</li>
                    </a>
                </ul>
            </li>
        </ul>
    </nav>
{% endblock %}

core/templates/core/language_expanded_search_table_layout.html
{% load cl_filters work_util_tags %}

<table id="results_table">
    <thead>
    <tr></tr>
    <tr>
        <th>3-letter language code</th>
        <th>Alternative 2-letter code</th>
        <th>Language name</th>
        <th>Favourite?</th>
    </tr>
    </thead>
    <tbody>


    {% for r in search_results %}
        <tr class="selectable_entry {% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}"
            entry_id="{{ r.pk }}">

            <td>
                {{ r.code_639_3 }}
            </td>
            <td>
                {{ r.code_639_1 }}
            </td>
            <td class="language_name">
                {{ r.language_name }}
            </td>
            <td>
                <div class="fav_lang {{ r.cofkunionfavouritelanguage|yesno:',hiding' }}">
                    <b>Yes</b>
                    <br/>
                    Remove from favourites
                    <input class="fav_remove" type="submit" value="Remove"/>
                </div>
                <div class="non_fav_lang  {{ r.cofkunionfavouritelanguage|yesno:'hiding,' }}">
                    Add to favourites
                    <input class="fav_add" type="submit" value="Add"/>
                </div>


                {% if r.cofkunionlanguageofmanifestation_set.first %}
                {% else %}
                {% endif %}

            </td>

        </tr>
    {% endfor %}
    </tbody>

</table>


<script>

    function submit_fav_form(action, target) {
        let tr_jqe = $(target).closest('tr')
        let lang_id = tr_jqe.attr('entry_id')
        $.ajax({
            url: action,
            type: 'POST',
            data: {
                'code_639_3': lang_id,
            },
            headers: {
                'X-CSRFToken': getCookie('csrftoken'),
            },
            dataType: 'json',
            success: (data) => {
                let action_name = action === 'fav_remove' ? 'removed from' : 'added to';
                let display_name = tr_jqe.find('.language_name').html().trim();
                $('#user_messages').html($('<h1>').text(`${display_name} ${action_name} favourites`))
                $(tr_jqe).find('.fav_lang, .non_fav_lang').toggleClass('hiding');
            }
        })
    }


    $(() => {
        $('.fav_remove').click((e) => {
            e.preventDefault()
            submit_fav_form('fav_remove', e.target,)
        });
        $('.fav_add').click((e) => {
            e.preventDefault()
            submit_fav_form('fav_add', e.target,)
        });

    });

</script>

core/templates/core/merge_confirm.html
{% extends "core/emlo_logined.html" %}

{% block content %}
    <h1> Merge -- Confirm </h1>
    <form method="post" action="{{ merge_action_url }}">
        {% csrf_token %}
        <div class="merge-div">

            <h1>Selected</h1>
            {% include "core/component/merge_box.html" with merge_context=selected %}
            <input type="hidden" name="selected_pk" value="{{ selected.model_pk }}">


            <h1>Others</h1>
            {% for m in others %}
                {% include "core/component/merge_box.html" with merge_context=m no_details=True %}
                <input type="hidden" name="merge_pk" value="{{ m.model_pk }}">
            {% endfor %}
        </div>
        <div class="sticky-bottom row-no-margin actionbox">
            <button class="cancel" name="action_type" value="cancel">Cancel</button>
            <button class="save" name="action_type" value="confirm">Confirm</button>
        </div>
    </form>
{% endblock %}